CREATE TABLE boards
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                              NOT NULL,
    slug        VARCHAR(20)                              NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_boards PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    topic_id   INTEGER                                  NOT NULL,
    post_num   INTEGER                                  NOT NULL,
    content    TEXT                                     NOT NULL,
    is_edited  BOOLEAN                                  NOT NULL,
    is_deleted BOOLEAN                                  NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE topics
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_id     INTEGER                                  NOT NULL,
    title        VARCHAR(100)                             NOT NULL,
    post_count   INTEGER,
    last_post_at TIMESTAMP WITHOUT TIME ZONE,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_topics PRIMARY KEY (id)
);

ALTER TABLE boards
    ADD CONSTRAINT uc_boards_slug UNIQUE (slug);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topics (id);

ALTER TABLE topics
    ADD CONSTRAINT FK_TOPICS_ON_BOARD FOREIGN KEY (board_id) REFERENCES boards (id);